### ISSUE TITLE
Github Branches remote: Not Found

### ISSUE THREAD

**Issue by leebaroneau** [adrianjost/files-sync-action#254]
Hi I'm trying to sync one repo main branch to another repo staging branch.

My files-sync-action.yml is as follows:
```
name: Sync
"on":
  schedule:
    - cron: "0 3 * * *"
  push:
    branches:
      - main
jobs:
  files:
    name: Files
    runs-on: ubuntu-latest
    steps:
      - uses: adrianjost/files-sync-action@v1.0.1
        with:
          GITHUB_TOKEN: "${{ secrets.SYNC_GITHUB_TOKEN }}"
          FILE_PATTERNS: |-
            snippets/c-dynamic-subtotal.liquid
            snippets/c-btm.liquid
            ^README.md
          TARGET_REPOS: |-
            Haverford-Brands/Haverford.com.au:wip
```
This is the the error I receive in Github actions

```
Run adrianjost/files-sync-action@v1.0.1
  with:
    GITHUB_TOKEN: ***
    FILE_PATTERNS: snippets/c-dynamic-subtotal.liquid
  snippets/c-btm.liquid
  ^README.md
    TARGET_REPOS: Haverford-Brands/Haverford.com.au:wip
Context: {
  "COMMIT_MESSAGE": "Update file(s) from \"Haverford-Brands/Template-Repository\"",
  "DRY_RUN": false,
  "FILE_PATTERNS": [
    {},
    {},
    {}
  ],
  "GITHUB_TOKEN": "<secret>",
  "GIT_EMAIL": "leebaroneau@users.noreply.github.com",
  "GIT_USERNAME": "leebaroneau",
  "SKIP_CLEANUP": false,
  "SKIP_DELETE": false,
  "SRC_REPO": "Haverford-Brands/Template-Repository",
  "TARGET_REPOS": [
    "Haverford-Brands/Haverford.com.au:wip"
  ],
  "TMPDIR": "tmp-1695951768845"
}
Haverford-Brands/Template-Repository: EXEC: "git clone --depth 1 https://***@github.com/Haverford-Brands/Template-Repository.git tmp-1695951768845/Haverford-Brands/Template-Repository" IN "./"
Haverford-Brands/Template-Repository: OUTPUT: "null"
Haverford-Brands/Template-Repository: FILE_PATTERNS [
  "/snippets\\/c-dynamic-subtotal.liquid/",
  "/snippets\\/c-btm.liquid/",
  "/^README.md/"
]
Haverford-Brands/Template-Repository: MATCHING FILES: [
  "README.md",
  "snippets/c-btm.liquid",
  "snippets/c-dynamic-subtotal.liquid"
]
Haverford-Brands/Haverford.com.au:wip: EXEC: "git clone --depth 1 https://***@github.com/Haverford-Brands/Haverford.com.au:wip.git tmp-1695951768845/Haverford-Brands/Haverford.com.au:wip" IN "./"
Haverford-Brands/Haverford.com.au:wip: OUTPUT: "Error: Command failed: git clone --depth 1 https://***@github.com/Haverford-Brands/Haverford.com.au:wip.git tmp-1695951768845/Haverford-Brands/Haverford.com.au:wip
Cloning into 'tmp-1695951768845/Haverford-Brands/Haverford.com.au:wip'...
remote: Repository not found.
fatal: repository 'https://github.com/Haverford-Brands/Haverford.com.au:wip.git/' not found
"
node:internal/errors:857
  const err = new Error(message);
              ^

Error: Command failed: git clone --depth 1 https://***@github.com/Haverford-Brands/Haverford.com.au:wip.git tmp-1695951768845/Haverford-Brands/Haverford.com.au:wip
Cloning into 'tmp-1695951768845/Haverford-Brands/Haverford.com.au:wip'...
remote: Repository not found.
fatal: repository 'https://github.com/Haverford-Brands/Haverford.com.au:wip.git/' not found

    at ChildProcess.exithandler (node:child_process:40[2](https://github.com/Haverford-Brands/Template-Repository/actions/runs/6346196230/job/17239367994#step:2:2):12)
    at ChildProcess.emit (node:events:51[3](https://github.com/Haverford-Brands/Template-Repository/actions/runs/6346196230/job/17239367994#step:2:3):28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:30[4](https://github.com/Haverford-Brands/Template-Repository/actions/runs/6346196230/job/17239367994#step:2:4):[5](https://github.com/Haverford-Brands/Template-Repository/actions/runs/6346196230/job/17239367994#step:2:5)) {
  code: 128,
  killed: false,
  signal: null,
  cmd: 'git clone --depth 1 https://***@github.com/Haverford-Brands/Haverford.com.au:wip.git tmp-1[6](https://github.com/Haverford-Brands/Template-Repository/actions/runs/6346196230/job/17239367994#step:2:6)95951[7](https://github.com/Haverford-Brands/Template-Repository/actions/runs/6346196230/job/17239367994#step:2:7)6[8](https://github.com/Haverford-Brands/Template-Repository/actions/runs/6346196230/job/17239367994#step:2:9)8[45](https://github.com/Haverford-Brands/Template-Repository/actions/runs/6346196230/job/17239367994#step:2:46)/Haverford-Brands/Haverford.com.au:wip'
}
```
